var arts = {
    flameGrenade: {
        name: "Flame Grenade",
        weapon: "Assault Rifle",
        class: "Drifter 1",
        range: "Target: Single Enemy",
        attribute: "Thermal",
        tp: 0,
        description: "Deals thermal damage + Inflicts Blaze + VS. TOPPLED TARGETS: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[300/400/500/600/700]%",
        hits: 1,
        additionalEffects: "Blaze [I/II/III/IV/V]",
        effectDuration: "15.0s",
        specialEffects: "Deals [50/75/100/125/150]% more damage to enemies inflicted with Topple."
    },
    assaultHammer: {
        name: "Assault Hammer",
        weapon: "Assault Rifle",
        class: "Drifter 1",
        range: "Target: Single Enemy",
        attribute: "Physical",
        tp: 0,
        description: "Deals physical damage + Inflicts Topple.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[50.0/46.0/44.0/42.0/40.0]s",
        hitScaling: "[300/375/450/525/600]%",
        hits: 1,
        additionalEffects: "Topple [I/II/III/IV/V]",
        effectDuration: "[4.0/4.5/5.0/5.5/6.0]s"
    },
    chromeArmor: {
        name: "Chrome Armor",
        weapon: "Knife",
        class: "Drifter 2",
        range: "Target: One Ally",
        tp: 0,
        description: "Grants Physical Res Up",
        cooldownBonus: "Immediate reuse",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        effects: "Physical Res Up [I/II/III/IV/V]",
        effectDuration: "15.0s"
    },
    slitEdge: {
        name: "Slit Edge",
        weapon: "Knife",
        class: "Drifter 4",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + FROM THE SIDE: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[12.0/10.1/9.1/8.1/7.2]s",
        hitScaling: "[125/150/175/200/225]%",
        hits: 1,
        specialEffects: "Deals [50/75/100/125/150]% more damage when attacking from the side."
    },
    infuriate: {
        name: "Infuriate",
        weapon: "Assault Rifle",
        class: "Drifter 6",
        range: "Target: Single Enemy",
        tp: 0,
        description: "Inflicts Taunt to draw the target's attacks.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[20.0/16.8/15.2/13.6/12.0]s",
        hits: 1,
        effects: "Taunt [I/II/III/IV/V]",
        effectDuration: "[10.0/12.0/14.0/16.0/18.0]s"
    },
    recuperate: {
        name: "Recuperate",
        weapon: "Knife",
        class: "Drifter 8",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Boosts evasion + Continually restores HP.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration + [20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Recuperate [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Boosts evasion. Recovers continual HP over time."
    },
    risingBlade: {
        name: "Rising Blade",
        weapon: "Longsword",
        class: "Striker 1",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + WHEN TAUNTED: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[15.0/12.6/11.4/10.2/9.0]s",
        hitScaling: "[100/125/150/175/200]%",
        hits: 3,
        specialEffects: "Deals [25/50/75/100/125]% more damage when an enemy is targeting you."
    },
    defensiveStance: {
        name: "Defensive Stance",
        weapon: "Longsword",
        class: "Striker 2",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Reduces damage taken + Continually restores HP + Reduces total melee attack.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Defensive Stance [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Reduces total melee attack. Reduces damage taken. Recovers continual HP over time."
    },
    powerDive: {
        name: "Power Dive",
        weapon: "Assault Rifle",
        class: "Striker 3",
        range: "Target: Self",
        tp: 0,
        description: "Grants Supercharge + Grants total evasion during execution.",
        cooldownBonus: "Buff tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        hits: 1,
        effects: "Supercharge [I/II/III/IV/V]",
        effectDuration: "30.0s"
    },
    tornadoBlade: {
        name: "Tornado Blade",
        weapon: "Longsword",
        class: "Striker 4",
        range: "Target: Self",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + WITH AN AURA: boosts TP.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[25/50/75/100/125]%",
        hits: 4,
        specialEffects: "Increases TP by [50/60/70/80/100] if it connects when you have an aura active."
    },
    furiousBlast: {
        name: "Furious Blast",
        weapon: "Assault Rifle",
        class: "Striker 6",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Boosts damage in melee combos.",
        cooldownBonus: "+[25/50] TP per hit",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[10/20/30/40/50]%",
        hits: 15,
        specialEffects: "Deals +[100/150/200/250/300]% more damage when triggering a melee combo."
    },
    magnumEdge: {
        name: "Magnum Edge",
        weapon: "Longsword",
        class: "Striker 8",
        range: "Target: Enemies Ahead",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Inflicts Physical Res Down.",
        cooldownBonus: "Debuff tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[200/250/300/350/400]%",
        hits: 1,
        additionalEffects: "Phys Res Down [I/I/II/II/III]",
        effectDuration: "20.0s"
    },
    offensiveStance: {
        name: "Offensive Stance",
        weapon: "Longsword",
        class: "Samurai Gunner 1",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Boosts melee accuracy + Boosts total melee attack + Increases damage taken.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Offensive Stance [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Boosts melee accuracy. Boosts total melee attack. Boosts damage taken."
    },
    burstGrenade: {
        name: "Burst Grenade",
        weapon: "Assault Rifle",
        class: "Samurai Gunner 1",
        range: "Target: Enemy Vicinity",
        attribute: "Thermal",
        tp: 1000,
        description: "[TP] Deals thermal damage + Inflicts Blaze + VS. TOPPLED TARGETS: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[750/900/1050/1200/1350]%",
        hits: 1,
        additionalEffects: "Blaze [I/I/II/II/III]",
        effectDuration: "15.0s",
        specialEffects: "Deals [200/225/250/275/300]% more damage to enemies inflicted with Topple."
    },
    decoyRound: {
        name: "Decoy Round",
        weapon: "Assault Rifle",
        class: "Samurai Gunner 2",
        range: "Target: Single Enemy",
        tp: 0,
        description: "Inflicts Taunt + WITH MORALE: boosts TP.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hits: 1,
        effects: "Taunt [I/II/III/IV/V]",
        effectDuration: "[10.0/12.0/14.0/16.0/18.0]s",
        specialEffects: "Increases TP by [100/150/200/250/300] x morale level."
    },
    flashGrenade: {
        name: "Flash Grenade",
        weapon: "Assault Rifle",
        class: "Samurai Gunner 3",
        range: "Target: Enemy Vicinity",
        attribute: "Electric",
        tp: 0,
        description: "Deals electric damage + Inflicts Blackout.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[20/25/30/35/40]%",
        hits: 1,
        additionalEffects: "Blackout [I/I/II/II/III]",
        effectDuration: "5.0s"
    },
    medicFree: {
        name: "Medic Free",
        weapon: "Assault Rifle",
        class: "Samurai Gunner 4",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Boosts debuff resistance + Auto-revives on incapacitation.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Medic Free [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Auto-recovers HP upon incapacitation. Boosts resistance to all debuffs."
    },
    assaultBreaker: {
        name: "Assault Breaker",
        weapon: "Assault Rifle",
        class: "Samurai Gunner 6",
        range: "Target: Single Enemy",
        attribute: "Physical",
        tp: 0,
        description: "Deals physical damage + FROM BEHIND: Inflicts Stun.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[200/250/300/350/400]%",
        hits: 1,
        specialEffects: "If used from Back, inflicts Stun [I/II/III/IV/V]"
    },
    burningSlash: {
        name: "Burning Slash",
        weapon: "Longsword",
        class: "Samurai Gunner 8",
        range: "Target: Enemies Ahead",
        attribute: "Thermal",
        tp: 0,
        description: "Deals thermal damage + Inflicts Thermal Res Down.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[125/150/175/200/225]%",
        hits: 2,
        additionalEffects: "Thermal Res Down [I/I/II/II/III]",
        effectDuration: "20.0s"
    },
    incendiaryEdge: {
        name: "Incendiary Edge",
        weapon: "Longsword",
        class: "Duelist 1",
        range: "Target: Single Enemy",
        attribute: "Thermal",
        tp: 1000,
        description: "[TP] Deals thermal damage + Boosts damage in melee combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[300/400/500/600/700]%",
        hits: 3,
        specialEffects: "Deals [100/125/150/175/200]% more damage when triggering a melee combo."
    },
    gunforce: {
        name: "Gunforce",
        weapon: "Assault Rifle",
        class: "Duelist 2",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Boosts ranged attack + Boosts critical chance + Reduces secondary cooldown.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Gunforce [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Boosts ranged attack. Boosts critical chance. Reduces secondary cooldown."
    },
    takedownShot: {
        name: "Takedown Shot",
        weapon: "Assault Rifle",
        class: "Duelist 4",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Inflicts Topple on mechanoids.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        hitScaling: "[50/75/100/125/150]%",
        hits: 6,
        specialEffects: "Inflicts Topple [I/II/III/IV/V] on mechanoid enemies."
    },
    samuraiSoul: {
        name: "Samurai Soul",
        weapon: "Longsword",
        class: "Duelist 6",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Adds AOE to melee AAs + Boosts AAs upon taking damage + Reduces secondary CD.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Samurai Soul [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Adds an area of effect to melee auto-attacks. Boosts auto-attack damage upon taking damage. Reduces secondary cooldown."
    },
    lastStand: {
        name: "Last Stand",
        weapon: "Assault Rifle",
        class: "Duelist 8",
        range: "Target: Other Allies",
        tp: 1000,
        description: "[TP] Boosts allies' TP.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[90.0/75.6/68.4/61.2/54.0]s",
        specialEffects: "Grants [1000/1250/1500/1750/2000] TP to party members fighting on foot."
    },
    wildDown: {
        name: "Wild Down",
        weapon: "Shield",
        class: "Shield Trooper 1",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 1000,
        description: "[TP] Deals weapon damage + Inflicts Topple.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[50.0/42.0/38.0/34.0/30.0]s",
        hitScaling: "[150/200/250/300/350]%",
        hits: 1,
        additionalEffects: "Topple [I/II/III/IV/V]",
        effectDuration: "[4.0/4.5/5.0/5.5/6.0]s"
    },
    missileVolley: {
        name: "Missile Volley",
        weapon: "Gatling Gun",
        class: "Shield Trooper 1",
        range: "Target: Enemies Ahead",
        attribute: "Thermal",
        tp: 0,
        description: "Deals thermal damage + Inflicts Thermal Res Down.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[200/250/300/350/400]%",
        hits: 6,
        additionalEffects: "Thermal Res Down [I/I/II/II/III]",
        effectDuration: "20.0s"
    },
    flameCloak: {
        name: "Flame Cloak",
        weapon: "Shield",
        class: "Shield Trooper 2",
        range: "Target: Nearby Allies",
        tp: 0,
        description: "Grants Thermal Res Up",
        cooldownBonus: "Buff tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[45.0/37.8/34.2/30.6/27.0]s",
        effects: "Thermal Res Up [I/I/II/II/III]",
        effectDuration: "15.0s"
    },
    ironPrison: {
        name: "Iron Prison",
        weapon: "Shield",
        class: "Shield Trooper 3",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Grants Physical Res Up + Enables proximity spike damage.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Iron Prison [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Boosts physical resistance. Grants proximity spike effects."
    },
    wildSmash: {
        name: "Wild Smash",
        weapon: "Shield",
        class: "Shield Trooper 4",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + VS. TOPPLED TARGETS: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[20.0/16.8/15.2/13.6/12.0]s",
        hitScaling: "[50/75/100/125/150]%",
        hits: 3,
        specialEffects: "Deals [25/50/75/100/125]% more damage to enemies inflicted with Topple."
    },
    trashTalk: {
        name: "Trash Talk",
        weapon: "Shield",
        class: "Shield Trooper 5",
        range: "Target: Nearby Enemies",
        tp: 0,
        description: "Inflicts Taunt + WITH MORALE: boosts TP.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hits: 1,
        effects: "Taunt [I/I/II/II/III]",
        effectDuration: "[10.0/10.0/12.0/12.0/14.0]s",
        specialEffects: "Increases TP by [100/125/150/175/200] x morale level."
    },
    bulletStorm: {
        name: "Bullet Storm",
        weapon: "Gatling Gun",
        class: "Shield Trooper 7",
        range: "Target: Enemies Ahead",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Inflicts Flinch on humanoids.",
        cooldownBonus: "+[25/50] TP per hit",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[80/100/120/140/160]%",
        hits: 12,
        specialEffects: "Grants a [20/25/30/40/50]% chance of inflicting Flinch [I/I/II/II/III] on humanoid enemies."
    },
    hellfire: {
        name: "Hellfire",
        weapon: "Gatling Gun",
        class: "Bastion Warrior 1",
        range: "Target: Enemies Ahead",
        attribute: "Weapon",
        tp: 1000,
        description: "[TP] Deals weapon damage + WITH AN AURA: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[200/250/300/350/400]%",
        hits: 12,
        specialEffects: "Deals [100/125/150/175/200]% more damage when you have an aura active."
    },
    shieldWall: {
        name: "Shield Wall",
        weapon: "Shield",
        class: "Bastion Warrior 2",
        range: "Target: Nearby Allies",
        tp: 0,
        description: "Grants Barrier.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[90.0/75.6/68.4/61.2/54.0]s",
        effects: "Barrier [I/I/II/II/III]",
        effectDuration: "30.0s"
    },
    enhancedStand: {
        name: "Enhanced Stand",
        weapon: "Gatling Gun",
        class: "Bastion Warrior 2",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Boosts auto-attack damage + Continually restores HP.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Enhanced Stand [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Boosts auto-attack attack power. Recovers continual HP over time."
    },
    realityRift: {
        name: "Reality Rift",
        weapon: "Shield",
        class: "Bastion Warrior 3",
        range: "Target: Enemies Ahead",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Inflicts Slow Arts.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[125/150/175/200/225]%",
        hits: 1,
        additionalEffects: "Slow Arts [I/I/II/II/III]",
        effectDuration: "20.0s"
    },
    thermalPayload: {
        name: "Thermal Payload",
        weapon: "Gatling Gun",
        class: "Bastion Warrior 4",
        range: "Target: Single Enemy",
        attribute: "Thermal",
        tp: 1000,
        description: "[TP] Deals thermal damage + VS. TOPPLED TARGETS: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[500/600/700/800/900]%",
        hits: 6,
        specialEffects: "Deals [100/125/150/175/200]% more damage to enemies inflicted with Topple."
    },
    bombardier: {
        name: "Bombardier",
        weapon: "Shield",
        class: "Bastion Warrior 6",
        range: "Target: Nearby Enemies",
        attribute: "Thermal",
        tp: 0,
        description: "Deals thermal damage + Inflicts Blaze.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[125/150/175/200/225]%",
        hits: 1,
        additionalEffects: "Blaze [I/I/II/II/III]",
        effectDuration: "15.0s"
    },
    coolOff: {
        name: "Cool Off",
        weapon: "Gatling Gun",
        class: "Bastion Warrior 7",
        range: "Target: Self",
        tp: 0,
        description: "Removes debuffs + WITH AN AURA: consumes aura to yield TP.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        specialEffects: "Consumes your currently active aura to yield [1000/1250/1500/1750/2000] TP."
    },
    supershield: {
        name: "Supershield",
        weapon: "Shield",
        class: "Bastion Warrior 8",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Reflects physical attacks + Reduces damage taken + Nullifies Stun.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Supershield [I/II/III/IV/V]",
        effectDuration: "[10.0/12.0/14.0/16.0/18.0]s",
        auraEffects: "Reflects physical damage. Reduces damage taken. Negates the effects of Stun."
    },
    backSlash: {
        name: "Back Slash",
        weapon: "Dual Swords",
        class: "Commando 1",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage +    FROM BEHIND: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[15.0/12.6/11.4/10.2/9.0]s",
        hitScaling: "[200/250/300/350/400]%",
        hits: 1,
        specialEffects: "Deals [200/225/250/275/300]% more damage when attacking from behind."
    },
    earlyBird: {
        name: "Early Bird",
        weapon: "Dual Guns",
        class: "Commando 1",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Raises Critical Power tier + Boosts critical chance + Boosts evasion.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Early Bird [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Raises the tier of an active Critical Power buff. Boosts critical chance. Boosts evasion."
    },
    streamEdge: {
        name: "Stream Edge",
        weapon: "Dual Swords",
        class: "Commando 2",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 1000,
        description: "[TP] Deals weapon damage + Boosts damage in ranged combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[200/250/300/350/400]%",
        hits: 6,
        specialEffects: "Deals [100/125/150/175/200]% more damage when triggering a ranged combo."
    },
    slidingSlinger: {
        name: "Sliding Slinger",
        weapon: "Dual Guns",
        class: "Commando 2",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + FROM THE SIDE: boosts TP.",
        cooldownBonus: "+[25/50] TP per hit",
        cooldown: "[20.0/16.8/15.2/13.6/12.0]s",
        hitScaling: "[50/75/100/125/150]%",
        hits: 6,
        specialEffects: "Increases TP by [10/15/20/25/30] when attacking from the side."
    },
    upperHand: {
        name: "Upper Hand",
        weapon: "Dual Swords",
        class: "Commando 4",
        range: "Target: Self",
        tp: 0,
        description: "Grants Critical Power.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        effects: "Critical Power [I/II/III/IV/V]",
        effectDuration: "20.0s"
    },
    shadowrunner: {
        name: "Shadowrunner",
        weapon: "Dual Swords",
        class: "Commando 6",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Boosts potential + FROM BEHIND: boosts damage + Disables enemy detection.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Shadowrunner [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Boosts potential. Prevents detection from enemies. Boosts damage dealt from behind."
    },
    sideSlash: {
        name: "Side Slash",
        weapon: "Dual Swords",
        class: "Winged Viper 1",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Inflicts Fatigue + FROM THE SIDE: boosts damage.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[20.0/16.8/15.2/13.6/12.0]s",
        hitScaling: "[150/200/250/300/350]%",
        hits: 2,
        additionalEffects: "Fatigue [I/II/III/IV/V]",
        effectDuration: "20.0s",
        specialEffects: "Deals [50/75/100/125/150]% more damage when attacking from the side."
    },
    thirstyEdge: {
        name: "Thirsty Edge",
        weapon: "Dual Swords",
        class: "Winged Viper 2",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Restores HP when landing melee attacks.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Thirsty Edge [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Recovers HP when landing melee attacks."
    },
    violentStreak: {
        name: "Violent Streak",
        weapon: "Dual Guns",
        class: "Winged Viper 3",
        range: "Target: Nearby Enemies",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Boosts TP with criticals.",
        cooldownBonus: "+[25/50] TP per hit",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[150/200/250/300/350]%",
        hits: 5,
        specialEffects: "Increases TP by [50/60/70/80/100] when landing a critical hit."
    },
    bloodSacrifice: {
        name: "Blood Sacrifice",
        weapon: "Dual Swords",
        class: "Winged Viper 4",
        range: "Target: Self",
        tp: 0,
        description: "Halves current HP to boost TP by 1000.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[45.0/37.8/34.2/30.6/27.0]s",
        extraEffects: "Halves current HP to increase TP by 1000."
    },
    killingMachine: {
        name: "Killing Machine",
        weapon: "Dual Swords",
        class: "Winged Viper 6",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Boosts melee accuracy + Boosts melee attack + Boosts potential.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Killing Machine [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Boosts melee accuracy. Boosts melee attack. Boosts potential."
    },
    primer: {
        name: "Primer",
        weapon: "Dual Guns",
        class: "Winged Viper 8",
        range: "Target: Self",
        tp: 0,
        description: "Grants Critical Power + Boosts TP.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        effects: "Critical Power [I/II/III/IV/V]",
        effectDuration: "20.0s",
        specialEffects: "Increases TP by 200.",
    },
    electricSurge: {
        name: "Electric Surge",
        weapon: "Dual Swords",
        class: "Full Metal Jaguar 1",
        range: "Target: Enemies Ahead",
        attribute: "Ether",
        tp: 0,
        description: "Deals ether damage. Lower HP = higher damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[150/175/200/225/250]%",
        hits: 3,
        specialEffects: "The lower your current HP percentage, the higher the damage dealt."
    },
    ghostwalker: {
        name: "Ghostwalker",
        weapon: "Dual Guns",
        class: "Full Metal Jaguar 2",
        range: "Target: Self",
        tp: 0,
        description: "Grants Decoy.",
        cooldownBonus: "Buff tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[90.0/75.6/68.4/61.2/54.0]s",
        effects: "Decoy [I/II/III/IV/V]",
        effectDuration: "30.0s"
    },
    executioner: {
        name: "Executioner",
        weapon: "Dual Guns",
        class: "Full Metal Jaguar 4",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 1000,
        description: "[TP] Deals weapon damage + Boosts damage in ranged combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[45.0/37.8/34.2/30.6/27.0]s",
        hitScaling: "[100/150/200/250/300]%",
        hits: 12,
        specialEffects: "Deals [100/125/150/175/200]% more damage when triggering a ranged combo."
    },
    combatLimbo: {
        name: "Combat Limbo",
        weapon: "Dual Guns",
        class: "Full Metal Jaguar 6",
        range: "Target: Self",
        tp: 0,
        description: "Grants Effect Stasis.",
        cooldownBonus: "Buff tier +[1/2] / Effect duration +[10/20]s",
        cooldown: "[120.0/100.8/91.2/81.6/72.0]s",
        effects: "Effect Stasis [I/II/III/IV/V]",
        effectDuration: "[10.0/12.0/14.0/16.0/18.0]s"
    },
    hundredShells: {
        name: "Hundred Shells",
        weapon: "Dual Swords",
        class: "Full Metal Jaguar 8",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 1000,
        description: "[TP] Deals weapon damage + FROM BEHIND: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[50/75/100/125/150]%",
        hits: 14,
        specialEffects: "Deals [100/125/150/175/200]% more damage when attacking from behind."
    },
    arcingHorn: {
        name: "Arcing Horn",
        weapon: "Javelin",
        class: "Partisan Eagle 1",
        range: "Target: Single Enemy",
        attribute: "Electric",
        tp: 0,
        description: "Deals electric damage + Inflicts Electric Res Down + Boosts damage in melee combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[20.0/16.8/15.2/13.6/12.0]s",
        hitScaling: "[250/300/350/400/450]%",
        hits: 1,
        additionalEffects: "Electric Res Down [I/II/III/IV/V]",
        effectDuration: "20.0s",
        specialEffects: "Deals [30/60/90/120/150]% more damage when triggering a melee combo."
    },
    shrapnel: {
        name: "Shrapnel",
        weapon: "Sniper Rifle",
        class: "Partisan Eagle 1",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Boosts appendage damage",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[500/600/700/800/900]%",
        hits: 1,
        specialEffects: "Deals [100/125/150/175/200]% more damage to appendages."
    },
    eagleEye: {
        name: "Eagle Eye",
        weapon: "Sniper Rifle",
        class: "Partisan Eagle 2",
        range: "Target: Nearby Allies",
        tp: 0,
        description: "Grants Ranged Accuracy Up + Grants Ranged Attack Up.",
        cooldownBonus: "Buff tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        effects: "Ranged Accuracy Up [I/I/II/II/III]",
        effectDuration: "20.0s",
        specialEffects: "Grants Ranged Attack Up [I/II/III/IV/V]."
    },
    raijin: {
        name: "Raijin",
        weapon: "Javelin",
        class: "Partisan Eagle 3",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Boosts critical chance + Restores HP when using Arts + Reflects electric attacks.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Raijin [I/II/III/IV/V]",
        effectDuration: "[10.0/12.0/14.0/16.0/18.0]s",
        auraEffects: "Boosts critical chance. Recovers HP when using Arts. Reflects electric damage."
    },
    firstDown: {
        name: "First Down",
        weapon: "Sniper Rifle",
        class: "Partisan Eagle 4",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Inflicts Topple on Humanoids.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        hitScaling: "[300/400/500/600/700]%",
        hits: 1,
        specialEffects: "Inflicts Topple [I/II/III/IV/V] on humanoid enemies."
    },
    spiralHorn: {
        name: "Spiral Horn",
        weapon: "Javelin",
        class: "Partisan Eagle 6",
        range: "Target: Enemies Ahead",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Inflicts Physical Res Down + Boosts damage in melee combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[50/75/100/125/150]%",
        hits: 1,
        additionalEffects: "Physical Res Down [I/I/II/II/III]",
        effectDuration: "20.0s",
        specialEffects: "Deals [25/50/75/100/125]% more damage when triggering a melee combo."
    },
    intercept: {
        name: "Intercept",
        weapon: "Sniper Rifle",
        class: "Partisan Eagle 8",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Inflicts Stun.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[200/250/300/350/400]%",
        hits: 1,
        additionalEffects: "Stun [I/II/III/IV/V]",
        effectDuration: "[2.0/2.5/3.0/3.5/4.0]s"
    },
    overwhelm: {
        name: "Overwhelm",
        weapon: "Javelin",
        class: "Astral Crusader 1",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Inflicts Fatigue + Higher HP = higher damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[20.0/16.8/15.2/13.6/12.0]s",
        hitScaling: "[50/75/100/125/150]%",
        hits: 3,
        additionalEffects: "Fatigue [I/II/III/IV/V]",
        effectDuration: "20.0s",
        specialEffects: "The higher your current HP percentage, the higher the damage dealt."
    },
    hawkeye: {
        name: "Hawkeye",
        weapon: "Sniper Rifle",
        class: "Astral Crusader 1",
        range: "Target: Self",
        tp: 0,
        description: "Grants Critical Power.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        effects: "Critical Power [I/II/III/IV/V]",
        effectDuration: "20.0s"
    },
    speedDemon: {
        name: "Speed Demon",
        weapon: "Javelin",
        class: "Astral Crusader 2",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Reduces cooldown time while sprinting + Continually restores HP.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Speed Demon [I/II/III/IV/V]",
        effectDuration: "20.0s",
        auraEffects: "Reduces cooldown when sprinting, Recovers HP when sprinting."
    },
    sidewinder: {
        name: "Sidewinder",
        weapon: "Sniper Rifle",
        class: "Astral Crusader 3",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Inflicts Debuff Res Down.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[500/600/700/800/900]%",
        hits: 1,
        additionalEffects: "Debuff Res Down [I/II/III/IV/V]",
        effectDuration: "20.0s"
    },
    hairTrigger: {
        name: "Hair Trigger",
        weapon: "Javelin",
        class: "Astral Crusader 4",
        range: "Target: Self",
        tp: 0,
        description: "Grants Supercharge.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[45.0/37.8/34.2/30.6/27.0]s",
        effects: "Supercharge [I/II/III/IV/V]",
        effectDuration: "30.0s"
    },
    ghostSniper: {
        name: "Ghost Sniper",
        weapon: "Sniper Rifle",
        class: "Astral Crusader 6",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Boosts critical chance + Boosts TP with criticals + Boosts ranged accuracy.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Ghost Sniper [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Boosts critical chance, Boosts TP when landing critical hits, Boosts ranged accuracy."
    },
    tridentBuster: {
        name: "Trident Buster",
        weapon: "Javelin",
        class: "Astral Crusader 8",
        range: "Target: Enemies Ahead",
        attribute: "Electric",
        tp: 1000,
        description: "[TP] Deals electric damage + Inflicts Shock + Boosts damage in ranged combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[300/350/400/450/500]%",
        hits: 1,
        additionalEffects: "Shock [I/I/II/II/III]",
        effectDuration: "10.0s",
        specialEffects: "Deals [100/125/150/175/200]% more damage when triggering a ranged combo."
    },
    beamBarrage: {
        name: "Beam Barrage",
        weapon: "Raygun",
        class: "Enforcer 1",
        range: "Target: Enemies Ahead",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + WITH AN AURA: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[100/125/150/175/200]%",
        hits: 5,
        specialEffects: "Deals [50/75/100/125/150]% more damage when you have an aura active."
    },
    repair: {
        name: "Repair",
        weapon: "Knife",
        class: "Enforcer 3",
        range: "Target: One Ally",
        tp: 0,
        description: "Removes debuffs + Restores HP.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        specialEffects: "Recovers the target's HP by [5/6/7/8/10]%."
    },
    myopicScreen: {
        name: "Myopic Screen",
        weapon: "Raygun",
        class: "Enforcer 5",
        range: "Target: Enemies Ahead",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Inflicts Blackout.",
        cooldownBonus: "Debuff tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[100/125/150/175/200]%",
        hits: 3,
        additionalEffects: "Blackout [I/I/II/II/III]",
        effectDuration: "5.0s"
    },
    fullSpecs: {
        name: "Full Specs",
        weapon: "Knife",
        class: "Enforcer 7",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Boosts potential + Boosts ranged attack + Boosts ether resistance",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Full Spec [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Boosts potential. Boosts ranged attack. Boosts ether resistance."
    },
    screamer: {
        name: "Screamer",
        weapon: "Knife",
        class: "Psycorruptor 1",
        range: "Target: Enemy Vicinity",
        tp: 0,
        description: "Inflicts Sleep.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hits: 1,
        effects: "Sleep [I/I/II/II/III]",
        effectDuration: "[10.0/10.0/12.0/12.0/14.0]s"
    },
    subterfuge: {
        name: "Subterfuge",
        weapon: "Raygun",
        class: "Psycorruptor 2",
        range: "Target: Enemies Ahead",
        tp: 0,
        description: "Inflicts Debuff Res Down.",
        cooldownBonus: "Debuff tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hits: 3,
        effects: "Debuff Res Down [I/I/II/II/III]",
        effectDuration: "20.0s"
    },
    absorberSkin: {
        name: "Absorber Skin",
        weapon: "Knife",
        class: "Psycorruptor 3",
        range: "Target: One Ally",
        tp: 0,
        description: "Grants Barrier.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        effects: "Barrier [I/II/III/IV/V]",
        effectDuration: "30.0s"
    },
    etherBlast: {
        name: "Ether Blast",
        weapon: "Raygun",
        class: "Psycorruptor 5",
        range: "Target: Enemies Ahead",
        attribute: "Ether",
        tp: 1000,
        description: "[TP] Deasl ether damage + WITH AN AURA: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[200/300/400/500/600]%",
        hits: 3,
        specialEffects: "Deals [100/125/150/175/200]% more damage when you have an aura active."
    },
    brainjack: {
        name: "Brainjack",
        weapon: "Knife",
        class: "Psycorruptor 7",
        range: "Target: Single Enemy",
        tp: 1000,
        description: "[TP] Seizes control of the targeted enemy and turns it into an ally.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        hits: 1,
        effects: "Control [I/II/III/IV/V]",
        effectDuration: "[20.0/30.0/40.0/50.0/60.0]s"
    },
    dispel: {
        name: "Dispel",
        weapon: "Knife",
        class: "Mastermind 1",
        range: "Target: Single Enemy",
        attribute: "Ether",
        tp: 1000,
        description: "[TP] Deals ether damage + Randomly removes one buff from the target",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[200/250/300/350/400]%",
        hits: 1,
        specialEffects: "Removes a random buff from the target."
    },
    gravityBlast: {
        name: "Gravity Blast",
        weapon: "Raygun",
        class: "Mastermind 1",
        range: "Target: Single Enemy",
        attribute: "Gravity",
        tp: 0,
        description: "Deals gravity damage + Inflicts Topple.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[80.0/67.2/60.8/54.4/48.0]s",
        hitScaling: "[300/350/400/450/500]%",
        hits: 1,
        additionalEffects: "Topple [I/II/III/IV/V]",
        effectDuration: "[4.0/4.5/5.0/5.5/6.0]s"
    },
    gravityCloak: {
        name: "Gravity Cloak",
        weapon: "Raygun",
        class: "Mastermind 2",
        range: "Target: Single Enemy",
        tp: 0,
        description: "Grants Gravity Res Up.",
        cooldownBonus: "Buff tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[45.0/37.8/34.2/30.6/27.0]s",
        effects: "Gravity Res Up [I/I/II/II/III]",
        effectDuration: "15.0s"
    },
    servantSacrifice: {
        name: "Servant Sacrifice",
        weapon: "Knife",
        class: "Mastermind 3",
        range: "Target: Self",
        tp: 0,
        description: "Boosts HP and TP when controlling a target + Sometimes destroys the target.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        specialEffects: "Increases HP by [10/20/30/40/50]% and TP by [10/20/30/40/50]%."
    },
    energySource: {
        name: "Energy Source",
        weapon: "Knife",
        class: "Mastermind 4",
        range: "Target: One Ally",
        tp: 1000,
        description: "[TP] Boosts TP + Boosts potential.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        effects: "Potential Up [I/II/III/IV/V]",
        effectDuration: "20.0s",
        specialEffects: "Increases the target's TP by 1000."
    },
    blackButterfly: {
        name: "Black Butterfly",
        weapon: "Knife",
        class: "Mastermind 6",
        range: "Target: Single Enemy",
        attribute: "Ether",
        tp: 0,
        description: "Deals ether damage + Inflicts Ether Res Down + Shortens aura effect time.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[100/150/200/250/300]%",
        hits: 4,
        additionalEffects: "Ether Res Down [I/II/III/IV/V]",
        effectDuration: "20.0s",
        specialEffects: "Decreases the target's aura duration by [1/1/2/2/3] second(s)."
    },
    pathogenBlast: {
        name: "Pathogen Blast",
        weapon: "Raygun",
        class: "Mastermind 8",
        range: "Target: Enemies Ahead",
        tp: 0,
        description: "Inflicts Virus/",
        cooldownBonus: "Debuff tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        hits: 1,
        effects: "Virus [I/I/II/II/III]",
        effectDuration: "20.0s"
    },
    starfallBlade: {
        name: "Starfall Blade",
        weapon: "Photon Saber",
        class: "Blast Fencer 1",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Boosts damage in melee combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[15.0/12.6/11.4/10.2/9.0]s",
        hitScaling: "[100/125/150/175/200]% ",
        hits: 3,
        specialEffects: "Deals [25/50/75/100/125]% more damage when triggering a melee combo."
    },
    stellarRay: {
        name: "Stellar Ray",
        weapon: "Pscyho Launcher",
        class: "Blast Fencer 1",
        range: "Target: Nearby Enemies",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Inflicts Beam Res Down + WITH AN AURA: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[100/150/200/250/300]%",
        hits: 5,
        additionalEffects: "Beam Res Down [I/I/II/II/III]",
        effectDuration: "20.0s",
        specialEffects: "Deals [50/75/100/125/150]% more damage when you have an aura active."
    },
    geolibrium: {
        name: "Geolibrium",
        weapon: "Photon Saber",
        class: "Blast Fencer 2",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Boosts beam resistance + Continually restores HP + Nullifies terrain effects.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Geolibrium [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Boosts beam resistance. Recovers HP over time. Grants immunity to terrain damage."
    },
    lightningCloak: {
        name: "Lightning Cloak",
        weapon: "Psycho Launcher",
        class: "Blast Fencer 2",
        range: "Target: Nearby Allies",
        tp: 0,
        description: "Grants Electric Res Up",
        cooldownBonus: "Buff tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[45.0/37.8/34.2/30.6/27.0]s",
        effects: "Bolt Res Up [I/I/II/II/III]",
        effectDuration: "15.0s"
    },
    starfallRondo: {
        name: "Starfall Rondo",
        weapon: "Photon Saber",
        class: "Blast Fencer 3",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Boosts damage in melee combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[50/100/150/200/250]%",
        hits: 5,
        specialEffects: "Deals [25/50/75/100/125]% more damage when triggering a melee combo."
    },
    jetstream: {
        name: "Jetstream",
        weapon: "Psycho Launcher",
        class: "Blast Fencer 4",
        range: "Target: Enemies Ahead",
        attribute: "Ether",
        tp: 0,
        description: "Deals ether damage + Inflicts Stun.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[50.0/42.0/38.0/34.0/30.0]s",
        hitScaling: "[200250/300/350/400]%",
        hits: 1,
        additionalEffects: "Stun [I/I/II/II/III]",
        effectDuration: "[2.0/2.0/2.5/2.5/3.0]s"
    },
    astrolibrium: {
        name: "Astrolibrium",
        weapon: "Photon Saber",
        class: "Blast Fencer 6",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Reflects beam attack + Boosts beam damage.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Astrolibrium [I/II/III/IV/V]",
        effectDuration: "[10.0/12.0/14.0/16.0/18.0]s",
        auraEffects: "Reflects beam damage. Boosts beam damage."
    },
    shootingStar: {
        name: "Shooting Star",
        weapon: "Psycho Launcher",
        class: "Blast Fencer 8",
        range: "Target: Enemies Ahead",
        attribute: "Electric",
        tp: 0,
        description: "Deals electric damage + Inflicts Shock.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[600/700/800/900/1000]%",
        hits: 1,
        additionalEffects: "Shock [I/I/II/II/III]",
        effectDuration: "10.0s"
    },
    astralHeal: {
        name: "Astral Heal",
        weapon: "Photon Saber",
        class: "Galactic Knight 1",
        range: "Target: One Ally",
        tp: 1000,
        description: "[TP] Restores HP + WHEN IN SKELL: restores appendage HP.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[1000/1250/1500/1750/2000]%",
        specialEffects: "When targeting a Skell, all appendages recover [10/12/16/18/20]% HP."
    },
    astralProtection: {
        name: "Astral Protection",
        weapon: "Psycho Launcher",
        class: "Galactic Knight 1",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Boosts all attribute resistances + Restores HP when using Arts.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Astral Protection [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Boosts all resistances. Recovers HP when using Arts."
    },
    starfallBlossom: {
        name: "Starfall Blossom",
        weapon: "Photon Saber",
        class: "Galactic Knight 2",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + FROM THE FRONT: boosts TP.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[50/75/100/125/150]%",
        hits: 4,
        specialEffects: "Increases TP by [40/50/60/70/80] when attacking from the front."
    },
    astralPurge: {
        name: "Astral Purge",
        weapon: "Photon Saber",
        class: "Galactic Knight 3",
        range: "Target: One Ally",
        tp: 0,
        description: "Removes debuffs",
        cooldownBonus: "Immediate reuse",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s"
    },
    novalibrium: {
        name: "Novalibrium",
        weapon: "Photon Saber",
        class: "Galactic Knight 4",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Grants Supercharge upon taking damage + Enables counter spike damage.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Novalibrium [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Grants Supercharge upon taking damage. Grants counter spike effects."
    },
    starlightKick: {
        name: "Starlight Kick",
        weapon: "Psycho Launcher",
        class: "Galactic Knight 6",
        range: "Target: Single Enemy",
        attribute: "Gravity",
        tp: 1000,
        description: "[TP] Deals gravity damage + Inflicts Topple.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[80.0/67.2/60.8/54.4/48.0]s",
        hitScaling: "[800/1000/1200/1400/1600]%",
        hits: 1,
        additionalEffects: "Topple [I/II/III/IV/V]",
        effectDuration: "[4.0/4.5/5.0/5.5/6.0]s"
    },
    astralHorizon: {
        name: "Astral Horizon",
        weapon: "Photon Saber",
        class: "Galactic Knight 7",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Grants Astral Heal and Astral Purge to all allies + Expands area-of-effect attack range.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Astral Horizon [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Add an area of effect to Astral Purge. Adds an area of effect to Astral Heal. Boosts the range of area-of-effect attacks."
    },
    galacticCataclysm: {
        name: "Galactic Cataclysm",
        weapon: "Photon Saber",
        class: "Galactic Knight 8",
        range: "Target: Enemies Ahead",
        attribute: "Beam",
        tp: 1000,
        description: "[TP] Deals beam damage + WITH AN AURA: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8s/20.4/18.0]s",
        hitScaling: "[500/700/900/1100/1300]%",
        hits: 1,
        specialEffects: "Deals [200/225/250/275/300]% more damage when you have an aura active."
    },
    shadowstrike: {
        name: "Shadowstrike",
        weapon: "Dual Swords",
        class: "Elma, We Were Soldiers.",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Inflicts Stagger + FROM BEHIND: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[150/187/225/262/300]%",
        hits: 1,
        additionalEffects: "Stagger [I/II/III/IV/V]",
        effectDuration: "[5.0/6.0/7.0/8.0/9.0]s",
        specialEffects: "Deals [200/250/300/350/400]% more damage when attacking from behind."
    },
    ghostFactory: {
        name: "Ghost Factory",
        weapon: "Dual Guns",
        class: "Elma, Then and Now.",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Grants Decoy.",
        cooldownBonus: "Buff tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[45.0/37.8/34.2/30.6/27.0]s",
        effects: "Decoy [I/I/II/II/III]",
        effectDuration: "30.0s"
    },
    fireCarnival: {
        name: "Fire Carnival",
        weapon: "Gatling Gun",
        class: "Lin, The Repair Job.",
        range: "Target: Single Enemy",
        attribute: "Thermal",
        tp: 0,
        description: "Deals thermal damage",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[50/100/150/200/250]%",
        hits: 10,
    },
    drumRoll: {
        name: "Drum Roll",
        weapon: "Shield",
        class: "Lin, To Serve Nopon.",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 1000,
        description: "[TP] Deals weapon damage + Physical Res Down + IN MELEE COMBOS: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[150/200/250/300/350]%",
        hits: 8,
        additionalEffects: "Physical Res Down [I/II/III/IV/V]",
        effectDuration: "20.0s",
        specialEffects: "Deals [100/125/150/175/200]% more damage when triggering a melee combo."
    },
    smoothRecovery: {
        name: "Smooth Recovery",
        weapon: "Knife",
        class: "Irina, Renewed Will.",
        range: "Target: Nearby Allies",
        tp: 0,
        description: "Restores HP + Grants Evasion Up",
        cooldownBonus: "Immediate reuse",
        cooldown: "[45.0/37.8/34.2/30.6/27.0]s",
        hitScaling: "[500/600/700/800/1000]%",
        additionalEffects: "Evasion Up [I/I/II/II/III]",
        effectDuration: "20.0s"
    },
    quickCannon: {
        name: "Quick Cannon",
        weapon: "Assault Rifle",
        class: "Irina, Fathers and Sons.",
        range: "Target: Single Enemy",
        attribute: "Thermal",
        tp: 0,
        description: "Deals thermal damage + Inflicts Blaze + Boosts damage in melee combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[1000/1100/1200/1300/1400]%",
        hits: 1,
        additionalEffects: "Blaze [I/II/III/IV/V]",
        effectDuration: "15.0s",
        specialEffects: "Deals [50/75/100/125/150]% more damage when triggering a melee combo."
    },
    ultraslash: {
        name: "Ultraslash",
        weapon: "Longsword",
        class: "Gwin, Nine Lives.",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + FROM BEHIND: boosts damage",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[200/250/300/350/400]%",
        hits: 1,
        specialEffects: "Deals [200/250/300/350/400]% more damage when attacking from behind."
    },
    grenadeBlitz: {
        name: "Grenade Blitz",
        weapon: "Assault Rifle",
        class: "Gwin, Boot Camp.",
        range: "Target: Enemies Ahead",
        attribute: "Thermal",
        tp: 0,
        description: "Deals thermal damage",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[300/350/400/450/500]%",
        hits: 3,
    },
    starlightDuster: {
        name: "Starlight Duster",
        weapon: "Photon Saber",
        class: "Doug, Close Comrades.",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 1000,
        description: "[TP] Deals weapon damage + Inflicts Gravity Res Down + Boosts damage in melee combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        hitScaling: "[100/150/200/250/300]%",
        hits: 9,
        additionalEffects: "Gravity Res Down [I/II/III/IV/V]",
        effectDuration: "20.0s",
        specialEffects: "Deals [25/50/75/100/125]% more damage when triggering a melee combo."
    },
    phenomenon: {
        name: "Phenomenon",
        weapon: "Photon Saber",
        class: "Doug, Soldier of the Harriers.",
        range: "Target: Enemies Ahead",
        attribute: "Ether",
        tp: 0,
        description: "Deals ether damage + Inflicts Ether Res Down.",
        cooldownBonus: "Debuff tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[200/250/300/350/400]%",
        hits: 1,
        additionalEffects: "Ether Res Down [I/I/II/II/III]",
        effectDuration: "20.0s"
    },
    afterburner: {
        name: "Afterburner",
        weapon: "Sniper Rifle",
        class: "Lao, The Matchmaker",
        range: "Target: Enemy Vicinity",
        attribute: "Weapon",
        tp: 1000,
        description: "[TP] Deals weapon damage + Boosts damage in ranged combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[500/600/700/800/900]%",
        hits: 5,
        specialEffects: "Deals [100/125/150/175/200]% more damage when triggering a ranged combo."
    },
    balanceBreaker: {
        name: "Balance Breaker",
        weapon: "Javelin",
        class: "Lao, A Friend in Need",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Inflicts Stagger in melee combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[200/250/300/350/400]%",
        hits: 1,
        specialEffects: "Inflicts Stagger [I/II/III/IV/V] when triggering a melee combo."
    },
    mindstorm: {
        name: "Mindstorm",
        weapon: "Shield",
        class: "L, L's Conundrum.",
        range: "Target: Nearby Allies",
        tp: 0,
        description: "Restores HP + Grants Potential Up.",
        cooldownBonus: "Buff tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        hitScaling: "[350/500/650/800/1000]%",
        additionalEffects: "Potential Up [I/I/II/II/III]",
        effectDuration: "20.0s"
    },
    dualDynamo: {
        name: "Dual Dynamo",
        weapon: "Psycho Launchers",
        class: "L, The Nopon Heir.",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Boosts melee attack + Boosts ranged attack + Boosts potential.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Dual Dynamo [I/II/III/IV/V]",
        effectDuration: "[15.0/18.0/21.0/24.0/27.0]s",
        auraEffects: "Boosts melee attack, Boosts ranged attack, Boosts potential."
    },
    bulletTwister: {
        name: "Bullet Twister",
        weapon: "Gatling Gun",
        class: "Frye, Blitzkrieg.",
        range: "Target: Self",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + WITH AURA: boosts TP.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[100/150/200/250/300]%",
        hits: 8,
        specialEffects: "Increases TP by[20/30/40/50/60]if it connects when you have an aura active."
    },
    titanRecharge: {
        name: "Titan Recharge",
        weapon: "Gatling Gun",
        class: "Frye, Brotherly Love.",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Negates damage reflection + Restores HP when aura expires + Reduces secondary CD.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Titan Recharge [I/II/III/IV/V]",
        effectDuration: "[15.0/18.0/21.0/24.0/27.0]s",
        auraEffects: "Bypasses all enemy damage reflection, Reduces secondary cooldown, Recovers HP when your aura dissipates."
    },
    crisisZone: {
        name: "Crisis Zone",
        weapon: "Dual Swords",
        class: "Phog, Blitzkrieg.",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Reduces auto-attack intervals + Lower HP = higher damage + Continually reduces HP.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Crisis Zone [I/II/III/IV/V]",
        effectDuration: "[15.0/18.0/21.0/24.0/27.0]s",
        auraEffects: "Reduces auto-attack cooldown, Inflicts continual damage over time, the lower your HP, the higher the damage."
    },
    skyHigh: {
        name: "Sky High",
        weapon: "Dual Guns",
        class: "Phog, A Great Divide.",
        range: "Target: Single Enemy",
        attribute: "Physical",
        tp: 0,
        description: "Deals physical damage + Boosts damage in melee combos + Inflicts Stun.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[150/200/250/300/350]%",
        hits: 4,
        additionalEffects: "Stun [I/II/III/IV/V]",
        effectDuration: "[2.0/2.5/3.0/3.5/4.0]s",
        specialEffects: "Deals [25/50/75/100/125]% more damage when triggering a melee combo."
    },
    secondarySpeed: {
        name: "Secondary Speed",
        weapon: "Knife",
        class: "Hope, A False Hope.",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Reduces secondary cooldown + Reduces auto-attack intervals.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Secondary Speed [I/II/III/IV/V]",
        effectDuration: "[15.0/18.0/21.0/24.0/27.0]s",
        auraEffects: "Reduces secondary cooldown, Reduces auto-attack cooldown."
    },
    tacitCensure: {
        name: "Tacit Censure",
        weapon: "Psycho Launchers",
        class: "Hope, A Present for Hope.",
        range: "Target: Enemies Ahead",
        tp: 0,
        description: "Inflicts Virus",
        cooldownBonus: "Debuff tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        hits: 1,
        additionalEffects: "Virus [I/I/II/II/III]",
        effectDuration: "20.0s"
    },
    gravityLunge: {
        name: "Gravity Lunge",
        weapon: "Psycho Launchers",
        class: "Murderess, Serial Thriller.",
        range: "Target: Single Enemy",
        attribute: "Gravity",
        tp: 1000,
        description: "[TP] Deals Gravity damage + Inflicts Topple + Boosts damage in melee combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[100/150/200/250/300]%",
        hits: 10,
        additionalEffects: "Topple [I/II/III/IV/V]",
        specialEffects: "Deals [100/125/150/175/200]% more damage when triggering a melee combo."
    },
    seventhEdge: {
        name: "Seventh Edge",
        weapon: "Dual Swords",
        class: "Murderess, The Little Rich Girl.",
        range: "Target: Nearby Enemies",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Boosts TP in ranged combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[50/100/150/200/250]%",
        hits: 6,
        specialEffects: "Increases TP by [20/30/40/50/60] when triggering a ranged combo."
    },
    blossomDance: {
        name: "Blossom Dance",
        weapon: "Longsword",
        class: "Nagi, Reporting For Duty",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 1000,
        description: "[TP] Deals weapon damage + nullifies target's attribute resistances.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[300/400/500/600/700]%",
        hits: 6,
        additionalEffects: "Stagger [I/II/III/IV/V]",
        effectDuration: "[5.0/6.0/7.0/8.0/9.0]s",
        specialEffects: "Ignores enemy attribute resistances."
    },
    trueStreamEdge: {
        name: "True Stream Edge",
        weapon: "Longsword",
        class: "Nagi",
        range: "Target: Nearby Enemies",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + WITH MORALE: boosts TP.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[50/100/150/200/250]%",
        hits: 5,
        specialEffects: "Increases TP by [40/60/80/100/120] when at morale level 1 or higher."
    },
    zeroZero: {
        name: "Zero Zero",
        weapon: "Dual Guns",
        class: "Celica, Fitting In.",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Boosts TP in melee combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[100/125/150/175/200]%",
        hits: 10,
        specialEffects: "Increases TP by [20/30/40/50/60] when triggering a melee combo."
    },
    blackBane: {
        name: "Black Bane",
        weapon: "Knife",
        class: "Celica, New in New LA.",
        range: "Target: Single Enemy",
        attribute: "Ether",
        tp: 0,
        description: "Deals ether damage + More debuffs on Target = higher damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[200/250/300/350/400]%",
        hits: 1,
        specialEffects: "Deals [100/150/200/250/300]% more damage for every debuff on the enemy."
    },
    clarityRay: {
        name: "Clarity Ray",
        weapon: "Raygun",
        class: "Mia",
        range: "Target: Nearby Allies",
        tp: 0,
        description: "Removes Debuffs + Grants Ether Res Up.",
        cooldownBonus: "Buff tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        effects: "Ether Res Up [I/I/II/II/III]",
        effectDuration: "15.0s"
    },
    beamBomber: {
        name: "Beam Bomber",
        weapon: "Raygun",
        class: "Mia, Mia Grows Up",
        range: "Target: Enemies Ahead",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + WITH AN AURA: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[300/350/400/450/500]%",
        hits: 6,
        specialEffects: "Deals [50/75/100/125/150]% more damage when you have an aura active."
    },
    atomicHit: {
        name: "Atomic Hit",
        weapon: "Shield",
        class: "HB, The King of Fear",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Boosts appendage damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[200/300/400/500/600]%",
        hits: 1,
        specialEffects: "Deals [100/125/150/175/200]% more damage to appendages."
    },
    flamehand: {
        name: "Flamehand",
        weapon: "Shield",
        class: "HB, Climbing the Ladder",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Boosts debuff resistances + Nullifies terrain effects + Enables counter spike damage.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Flame Hand [I/II/III/IV/V]",
        effectDuration: "[15.0/18.0/21.0/24.0/27.0]s",
        auraEffects: "Boosts resistance to all debuffs, Grants counter spike effects, Grants immunity to terrain damage."
    },
    essenceExchange: {
        name: "Essence Exchange",
        weapon: "Photon Saber",
        class: "Yelv, Arms and the Man",
        range: "Target: Self",
        tp: 0,
        description: "Swaps current HP and TP.",
        cooldownBonus: "Immediate reuse",
        cooldown: "[90.0/75.6/68.4/61.2/54.0]s",
        extraEffects: "Switches current HP and TP amounts."
    },
    masterGunner: {
        name: "Master Gunner",
        weapon: "Raygun",
        class: "Yelv, Yelv's Partner",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Boosts ranged attack + Boosts potential + Boosts appendage damage.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Master Gunner [I/II/III/IV/V]",
        effectDuration: "[15.0/18.0/21.0/24.0/27.0]s",
        auraEffects: "Boosts damage dealt to appendages, Boosts ranged attack, Boosts potential."
    },
    overclock: {
        name: "Overclock",
        weapon: "Assault Rifle",
        class: "Alexa, What the Skell?!",
        range: "Target: Self",
        tp: 1000,
        description: "[TP] Restores HP when using Arts + Boosts fuel recovery of parked Skells.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Overclock [I/II/III/IV/V]",
        effectDuration: "[15.0/18.0/21.0/24.0/27.0]s",
        auraEffects: "Recovers HP when using Arts, Boosts fuel recovery when Skell is parked."
    },
    maximumVoltage: {
        name: "Maximum Voltage",
        weapon: "Javelin",
        class: "Alexa, Rapid Misfire",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 1000,
        description: "[TP] Deals weapon damage + AFTER LOSING SKELL: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        hitScaling: "[50/100/150/200/250]%",
        hits: 12,
        specialEffects: "Deals [600/650/700/750/800]% more damage if your Skell is destroyed during the battle."
    },
    vortex: {
        name: "Vortex",
        weapon: "Javelin",
        class: "Boze, Boze's Way",
        range: "Target: Nearby Enemies",
        attribute: "Electric",
        tp: 0,
        description: "Deals electric damage + Inflicts Stun in Melee Combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[40.0/33.6/30.4/27.2/24.0]s",
        hitScaling: "[150/200/250/300/350]%",
        hits: 1,
        specialEffects: "Inflicts Stun [I/I/II/II/III] when triggering a melee combo."
    },
    slayonet: {
        name: "Slayonet",
        weapon: "Sniper Rifle",
        class: "Boze, Boze's Ignorance.",
        range: "Target: Single Enemy",
        attribute: "Weapon",
        tp: 0,
        description: "Deals weapon damage + Boosts damage in Melee Combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[300/400/500/600/700]%",
        hits: 3,
        specialEffects: "Deals [25/50/75/100/125]% more damage when triggering a melee combo."
    },
    cannonBarrel: {
        name: "Cannon Barrel",
        weapon: "Multigun",
        class: "Yelv, Yelv's Partner",
        range: "Target: Enemy Vicinity",
        attribute: "Gravity",
        tp: 1000,
        description: "[TP] Deals gravity damage + Inflicts Topple + Boosts damage in Ranged Combos.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[500/625/750/875/1000]%",
        hits: 1,
        additionalEffects: "Topple [I/II/III/IV/V]",
        effectDuration: "[4.0/4.5/5.0/5.5/6]s",
        specialEffects: "Deals [100/125/150/175/200]% more damage when triggering a ranged combo."
    },
    missileBarrel: {
        name: "Missile Barrel",
        weapon: "Multigun",
        class: "Yelv, Yelv's Partner",
        range: "Target: Enemies Ahead",
        attribute: "Electric",
        tp: 0,
        description: "Deals electric damage + Inflicts Shock + WITH AURA: boosts damage.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[30.0/25.2/22.8/20.4/18.0]s",
        hitScaling: "[150/187/225/262/300]%",
        hits: 4,
        additionalEffects: "Shock [I/II/III/IV/V]",
        effectDuration: "10.0s",
        specialEffects: "Deals 150% more damage when you have an aura active."
    },
    sniperBarrel: {
        name: "Sniper Barrel",
        weapon: "Multigun",
        class: "Yelv, Yelv's Partner",
        range: "Target: Enemies Ahead",
        attribute: "Ether",
        tp: 0,
        description: "Deals ether damage + VS SHOCKED TARGETS: Inflicts Stun.",
        cooldownBonus: "Damage +[250/400]%",
        cooldown: "[20.0/16.8/15.2/13.6/12.0]s",
        hitScaling: "[400/500/600/700/800]%",
        hits: 1,
        specialEffects: "Inflicts Stun [I/II/III/IV/V] on enemies inflicted with Shock."
    },
    boostBarrel: {
        name: "Boost Barrel",
        weapon: "Multigun",
        class: "Yelv, Yelv's Partner",
        range: "Target: Target: Self",
        tp: 1000,
        description: "[TP] Reduces secondary cooldown + Faster AA + Boosts potential.",
        cooldownBonus: "Aura tier +[1/2] / Effect duration +[20/40]s",
        cooldown: "[60.0/50.4/45.6/40.8/36.0]s",
        aura: "Boost Barrel [I/II/III/IV/V]",
        effectDuration: "[20.0/22.0/24.0/26.0/28.0]s",
        auraEffects: "Reduces secondary cooldown, Reduces auto-attack cooldown, Boosts potential."
    }
}
